# Generated by Django 5.2.7 on 2025-10-21 22:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('price', models.BigIntegerField()),
                ('price_without_taxes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='category.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
            options={
                'unique_together': {('slug', 'seller')},
            },
        ),
    ]
