# Generated by Django 5.2.7 on 2025-10-16 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('surname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('USER', 'User')], default='USER', max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
