# Generated by Django 5.2.7 on 2025-10-21 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ancestor', models.PositiveIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('path_ids', models.CharField(blank=True, default='', max_length=1024)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('path',), name='unique_path')],
            },
        ),
    ]
